.table,.header,.companyName{
      border: 1px solid #C0C0C0;
      border-collapse:collapse;
      text-align:center;
}
.date{
        text-align:left;
        }
.companyName{
        background-color:#99CCFF
        
        
        }
.values,.totals{
         text-align:right;
         border: 1px solid #C0C0C0;
	     border-collapse:collapse;
        };
.totals{
        font-weight:bold;
        }